# Generated by Django 2.2 on 2021-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210520_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='resume',
            field=models.FileField(upload_to='mediafiles'),
        ),
    ]
