# Generated by Django 2.2 on 2021-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210520_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='resume',
            field=models.FileField(upload_to='assets/media'),
        ),
    ]
